---
output: html_document
date: "2023-08-11"
---
###Load data

```{r}
df_pre_match<-read.csv('data/df_pre_match.csv')
df_post_match<-read.csv('data/df_post_match.csv')

df_dis_pre_match<-read.csv('data/df_dis_pre_match.csv')
df_post_match_dis<-read.csv('data/df_post_match_dis.csv')

```

##spending
```{r}
mod_sp1_post = feols(lspend ~ port_treat|        
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_sp1_post)

mod_sp2_post = feols(lspend ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_sp2_post)

mod_sp_bin1_post = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_sp_bin1_post)

mod_sp_bin2_post = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_sp_bin2_post)



```



#customer
```{r}
mod_cus1_post = feols(lcus ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match_0)
summary(mod_cus1_post)

mod_cus2_post = feols(lcus ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_cus2_post)

mod_cus_bin1_post = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_cus_bin1_post)

mod_cus_bin2_post = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_cus_bin2_post)

```
```{r}
df_post_match<-df_post_match%>%
  mutate(cus_per_vis=raw_num_customers/(raw_visitor_counts+0.01))
```

```{r}
mod_cus2_post = feols(cus_per_vis~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match)
summary(mod_cus2_post)
```

###Disadvantaged
##spending
```{r}
mod_sp_dis1_post = feols(lspend ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_sp_dis1_post)

mod_sp_dis2_post = feols(lspend ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_sp_dis2_post)

mod_sp_dis_bin1_post = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_sp_dis_bin1_post)

mod_sp_dis_bin2_post = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_sp_dis_bin2_post)

```

#customer
```{r}
mod_cus_dis1_post = feols(lcus ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_cus_dis1_post)

mod_cus_dis2_post = feols(lcus ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_cus_dis2_post)

mod_cus_dis_bin1_post = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_cus_dis_bin1_post)

mod_cus_dis_bin2_post = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_post_match_dis)
summary(mod_cus_dis_bin2_post)

```
```{r}
# etable(list(mod_cus1,mod_cus2,mod_sp1,mod_sp2,mod_cus_dis1,mod_cus_dis2,mod_sp_dis1,mod_sp_dis2), tex=TRUE)
etable(list(mod_cus1,mod_cus2,mod_sp1,mod_sp2,mod_cus1_post,mod_cus2_post,mod_sp1_post,mod_sp2_post), tex=TRUE)
```

#disadvantaged
```{r}
etable(list(mod_cus_dis1,mod_cus_dis2,mod_sp_dis1,mod_sp_dis2,mod_cus_dis1_post,mod_cus_dis2_post,mod_sp_dis1_post,mod_sp_dis2_post), tex=TRUE)
```





####Below: not useful

##All: visits and visitors
```{r}

mod_vis1 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis1)

mod_vis2 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis2)

mod_vis_bin1 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)| 
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis_bin1)

mod_vis_bin2 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|     
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis_bin2)
```

##Disadvantaged: visits and visitors
```{r}

mod_vis_dis1 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis1)

mod_vis_dis2 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis2)

mod_vis_dis_bin1 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)| 
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis_bin1)

mod_vis_dis_bin2 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|     
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis_bin2)
```



