---
output: html_document
date: "2023-08-11"
---
###Load data

```{r}
df_pre_match<-read.csv('data/df_pre_match.csv')
df_post_match<-read.csv('data/df_post_match.csv')

df_dis_pre_match<-read.csv('data/df_dis_pre_match.csv')
df_post_match_dis<-read.csv('data/df_post_match_dis.csv')

```

##spending
```{r}
mod_sp1 = feols(lspend ~ port_treat|        
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp1)

mod_sp2 = feols(lspend ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp2)

mod_sp_bin1 = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp_bin1)

mod_sp_bin2 = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp_bin2)

```




#customer
```{r}
mod_cus1 = feols(lcus ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus1)

mod_cus2 = feols(lcus ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus2)

mod_cus_bin1 = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus_bin1)

mod_cus_bin2 = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus_bin2)

```


###Disadvantaged
##spending
```{r}
# mod_twfe_pre = feols(lspend ~ I(Post*ev_dis_treat_500)|
# 		  placekey+date+county_fips^date,
# 		  cluster = ~placekey,
# 		 data = df_dis_pre_match)
# summary(mod_twfe_pre)

mod_sp_dis1 = feols(lspend ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_dis1)

mod_sp_dis2 = feols(lspend ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_dis2)

mod_sp_dis_bin1 = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_dis_bin1)

mod_sp_dis_bin2 = feols(lspend ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_dis_bin2)

```

#customer
```{r}
mod_cus_dis1 = feols(lcus ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_dis1)

mod_cus_dis2 = feols(lcus ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_dis2)

mod_cus_dis_bin1 = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_dis_bin1)

mod_cus_dis_bin2 = feols(lcus ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_dis_bin2)

```
```{r}
etable(list(mod_cus1,mod_cus2,mod_sp1,mod_sp2,mod_cus_dis1,mod_cus_dis2,mod_sp_dis1,mod_sp_dis2), tex=TRUE)
```

```{r}
mod_cus_high2 = feols(log(high_cus+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus_high2)

mod_cus_med2 = feols(log(med_cus+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus_med2)

mod_cus_low2 = feols(log(low_cus+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_cus_low2)
```

```{r}
mod_sp_high2 = feols(log(high_spend+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp_high2)

mod_sp_med2 = feols(log(med_spend+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp_med2)

mod_sp_low2 = feols(log(low_spend+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_sp_low2)
```

```{r}
mod_cus_high_dis2 = feols(log(high_cus+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_high_dis2)

mod_cus_med_dis2 = feols(log(med_cus+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_med_dis2)

mod_cus_low_dis2 = feols(log(low_cus+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_cus_low_dis2)
```
```{r}
mod_sp_high_dis2 = feols(log(high_spend+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_high_dis2)

mod_sp_med_dis2 = feols(log(med_spend+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_med_dis2)

mod_sp_low_dis2 = feols(log(low_spend+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_sp_low_dis2)
```




####Below: not useful

##All: visits and visitors
```{r}

mod_vis1 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis1)

mod_vis2 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis2)

mod_vis_bin1 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)| 
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis_bin1)

mod_vis_bin2 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|     
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_pre_match)
summary(mod_vis_bin2)
```

##Disadvantaged: visits and visitors
```{r}

mod_vis_dis1 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis1)

mod_vis_dis2 = feols(log(raw_visit_counts+1) ~ port_treat|                
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis2)

mod_vis_dis_bin1 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)| 
		  placekey+date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis_bin1)

mod_vis_dis_bin2 = feols(log(raw_visit_counts+1) ~ I(Post*X0_100m)+I(Post*X100_200m)+I(Post*X200_300m)+I(Post*X300_400m)+I(Post*X400_500m)|     
		  placekey+date+county_fips^date,
		  cluster = ~placekey, 
		 data = df_dis_pre_match)
summary(mod_vis_dis_bin2)
```



