---
title: "03_distance_variation"
output: html_document
date: "2023-08-12"
---
```{r}
library(zoo)
library(broom)
```
```{r}
## all
out.sp2_post<-tidy(mod_sp_bin2_post)%>%
           dplyr::rename(Variable = term,
                  Coefficient = estimate,
                  SE = std.error) %>% dplyr::select(-statistic,
                              -p.value)%>%
  mutate(conf.low_95=Coefficient-1.645*SE,conf.high_95=Coefficient+1.645*SE,
         distance=seq(100, 500, by = 100),
         type='Spending')
#####
out.cus2_post<-tidy(mod_cus_bin2_post)%>%
           dplyr::rename(Variable = term,
                  Coefficient = estimate,
                  SE = std.error) %>% dplyr::select(-statistic,
                              -p.value)%>%
  mutate(conf.low_95=Coefficient-1.645*SE,conf.high_95=Coefficient+1.645*SE,
         distance=seq(100, 500, by = 100),
         type='Customer Count')

## disadvantaged
out.sp_dis2_post<-tidy(mod_sp_dis_bin2_post)%>%
           dplyr::rename(Variable = term,
                  Coefficient = estimate,
                  SE = std.error) %>% dplyr::select(-statistic,
                              -p.value)%>%
  mutate(conf.low_95=Coefficient-1.645*SE,conf.high_95=Coefficient+1.645*SE,
         distance=seq(100, 500, by = 100),
         type='Spending')


#####
out.cus_dis2_post<-tidy(mod_cus_dis_bin2_post)%>%
           dplyr::rename(Variable = term,
                  Coefficient = estimate,
                  SE = std.error) %>% dplyr::select(-statistic,
                              -p.value)%>%
  mutate(conf.low_95=Coefficient-1.645*SE,conf.high_95=Coefficient+1.645*SE,
         distance=seq(100, 500, by = 100),
         type='Customer Count')

distance_plot_full_post<-rbind(out.sp2_post,out.cus2_post,out.sp_dis2_post,out.cus_dis2_post)
distance_plot_all_post<-rbind(out.sp2_post,out.cus2_post)
distance_plot_all_post$type=factor(distance_plot_all_post$type,levels=c('Spending','Customer Count'))
distance_plot_dis_post<-rbind(out.sp_dis2_post,out.cus_dis2_post)
distance_plot_dis_post$type=factor(distance_plot_dis_post$type,levels=c('Spending','Customer Count'))
# distance_plot_full$type=factor(distance_plot_full$type,levels=c('Transit ridership','VMT'))
```


```{r}
ggplot(data=distance_plot_all_post,aes(x = distance, 
                    y = Coefficient,group=type,color=type,shape=type))+ 
        geom_point(position=position_dodge(width = 15),size=3,stroke=1) + 
          geom_line(position=position_dodge(width = 15),lwd = 0.7) +
        geom_linerange(aes(x = distance,
                     ymin = conf.low_95,
                     ymax = conf.high_95),alpha=0.7,
                   lwd = 0.5,position=position_dodge(width = 15))+
scale_color_manual('',values=c("#252A52","#66ADE5"),labels=c('Spending','Customer Count'),breaks=c('Spending','Customer Count'))+
  scale_shape_manual('',values = c(15,16),labels=c('Spending','Customer Count'),breaks=c('Spending','Customer Count'))+
   geom_hline(yintercept= 0,linetype='dashed')+
  labs(x="Distance Bin (m)")+
  theme(legend.position = c(0.6, 0.2))+
  theme(legend.key=element_blank(),
        # axis.ticks=element_blank(),
        axis.ticks.length=unit(.25, "cm"),
        axis.text=element_text(size=20,family="Arial"), 
        axis.text.x = element_text(vjust = 0.5, hjust=0.5,margin = margin(b = 12,t = 5)),
        axis.title.y = element_text(size=25, family="Arial",margin = margin(r = 12)),
        axis.title.y.right = element_text(size=25, family="Arial",margin = margin(l = 12, r = 5)),
        legend.box.background = element_rect(fill="transparent",colour=NA),
        legend.background = element_rect(fill='transparent'),
        legend.text=element_text(size=20, family="Arial",margin = margin(t = 3)), 
        legend.position = c(0.7,0.8),
        panel.background=element_blank(),
        panel.border = element_rect(colour = 'black', fill=NA),
        panel.grid.major = element_line(colour = "lightgrey"), 
        panel.grid.minor = element_line(colour = "lightgrey"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        # legend.box.background = element_rect(colour = "black"),
        text = element_text(size = 20),
        plot.margin = margin(t = 0.5,  # Top margin
                             r = 1,  # Right margin
                             b = 0.5,  # Bottom margin
                             l = 0.5, "cm"))
ggsave('plots/effect_distance_all_post.png', dpi = 800, width = 9, height = 7, units = "in")
```

```{r}
ggplot(data=distance_plot_dis_post,aes(x = distance, 
                    y = Coefficient,group=type,color=type,shape=type))+ 
        geom_point(position=position_dodge(width = 15),size=3,stroke=1) + 
          geom_line(position=position_dodge(width = 15),lwd = 0.7) +
        geom_linerange(aes(x = distance,
                     ymin = conf.low_95,
                     ymax = conf.high_95),alpha=0.7,
                   lwd = 0.5,position=position_dodge(width = 15))+
scale_color_manual('',values=c("#252A52","#66ADE5"),labels=c('Spending','Customer Count'),breaks=c('Spending','Customer Count'))+
  scale_shape_manual('',values = c(15,16),labels=c('Spending','Customer Count'),breaks=c('Spending','Customer Count'))+
   geom_hline(yintercept= 0,linetype='dashed')+
  labs(x="Distance Bin (m)")+
  theme(legend.position = c(0.6, 0.2))+
  theme(legend.key=element_blank(),
        # axis.ticks=element_blank(),
        axis.ticks.length=unit(.25, "cm"),
        axis.text=element_text(size=20,family="Arial"), 
        axis.text.x = element_text(vjust = 0.5, hjust=0.5,margin = margin(b = 12,t = 5)),
        axis.title.y = element_text(size=25, family="Arial",margin = margin(r = 12)),
        axis.title.y.right = element_text(size=25, family="Arial",margin = margin(l = 12, r = 5)),
        legend.box.background = element_rect(fill="transparent",colour=NA),
        legend.background = element_rect(fill='transparent'),
        legend.text=element_text(size=20, family="Arial",margin = margin(t = 3)), 
        legend.position = c(0.7,0.8),
        panel.background=element_blank(),
        panel.border = element_rect(colour = 'black', fill=NA),
        panel.grid.major = element_line(colour = "lightgrey"), 
        panel.grid.minor = element_line(colour = "lightgrey"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        # legend.box.background = element_rect(colour = "black"),
        text = element_text(size = 20),
        plot.margin = margin(t = 0.5,  # Top margin
                             r = 1,  # Right margin
                             b = 0.5,  # Bottom margin
                             l = 0.5, "cm"))
ggsave('plots/effect_distance_dis_post.png', dpi = 800, width = 9, height = 7, units = "in")
```

